import test from 'node:test';
import assert from 'node:assert/strict';
import {fetchPublicHtml,allowedUrl} from '../src/fetch-html.mjs';
import {sanitizeConversionInput,convertUrl,restoreLinks} from '../src/conversion.mjs';
const resolveHostname=async()=>['93.184.215.14'];
const html=()=>new Response('<article><h1>Self-authored</h1><p>Fixture</p></article>',{headers:{'content-type':'text/html'}});
test('unsafe destinations fail closed without requiring a fixed host allowlist',()=>{for(const value of ['http://article.example/','https://user:secret@article.example/','https://article.example:444/','https://127.0.0.1/','https://2130706433/','https://[::1]/','https://localhost/','https://article.example./','https://article.example/?token=secret'])assert.throws(()=>allowedUrl(value));assert.equal(allowedUrl('https://newsite.example/').hostname,'newsite.example');assert.throws(()=>allowedUrl('https://article.example/','article.example'));assert.equal(allowedUrl('https://article.example/a#ref').href,'https://article.example/a');});
test('fetch creates fixed headers and checks every manual redirect',async()=>{const calls=[];await fetchPublicHtml('https://article.example/a',{resolveHostname,fetcher:async(url,options)=>{calls.push({url,options});return calls.length===1?new Response('',{status:302,headers:{location:'https://redirect.example/b'}}):html();}});assert.equal(calls.length,2);for(const c of calls){assert.equal(c.options.redirect,'manual');assert.deepEqual(Object.keys(c.options.headers).sort(),['Accept','User-Agent']);assert.equal(c.options.method,'GET');}let count=0;await assert.rejects(fetchPublicHtml('https://article.example/a',{resolveHostname,fetcher:async()=>{count++;return new Response('',{status:302,headers:{location:'http://169.254.169.254/'}});}}));assert.equal(count,1);});
test('redirect loops, invalid MIME, large decoded response and HTTP denial are rejected',async()=>{await assert.rejects(fetchPublicHtml('https://article.example/a',{resolveHostname,fetcher:async()=>new Response('',{status:302,headers:{location:'/a'}})}));await assert.rejects(fetchPublicHtml('https://article.example/a',{resolveHostname,fetcher:async()=>new Response('img',{headers:{'content-type':'image/png'}})}));await assert.rejects(fetchPublicHtml('https://article.example/a',{resolveHostname,maxBytes:10,fetcher:async()=>html()}));await assert.rejects(fetchPublicHtml('https://article.example/a',{resolveHostname,fetcher:async()=>new Response('paywall',{status:403})}));});
test('sanitizer removes executable/resource-bearing HTML, attrs, base and metadata',()=>{const input='<title>Self-authored title</title><base href="http://localhost/"><meta content="https://evil.example/a"><script type="application/ld+json">secret</script><style>x</style><article onclick="evil()"><h1>本文</h1><p>文章 <a href="/source" onmouseover="evil()">出典</a></p><img src="https://evil.example/pixel"><iframe src="http://127.0.0.1/"></iframe><svg><image href="https://evil.example/x"/></svg><form><input value="private"></form></article>';
 const r=sanitizeConversionInput(input,'https://article.example/a');assert.equal(r.title,'Self-authored title');assert.deepEqual(r.links,['https://article.example/source']);assert.ok(r.html.includes('本文'));assert.ok(r.html.includes('#yomudake-link-0'));assert.ok(!/script|style|base|meta|onclick|onmouseover|iframe|img|svg|form|input|evil\.example|localhost|127\.0\.0\.1|secret|private/.test(r.html));assert.ok(!r.html.includes('href="https:'));
 assert.equal(restoreLinks('[出典](#yomudake-link-0)',r.links),'[出典](https://article.example/source)');});
test('conversion sends only sanitized HTML to binding and returns editable Markdown',async()=>{let calls=0;const env={AI:{async toMarkdown(file,options){calls++;assert.equal(file.name,'page.html');assert.equal(file.blob.type,'text/html');const html=await file.blob.text();assert.ok(!html.includes('evil.example'));assert.equal(options.conversionOptions.output.format,'markdown');return {format:'markdown',data:'# Self-authored\n\n[出典](#yomudake-link-0)'};}}};const result=await convertUrl('https://article.example/a',env,{resolveHostname,fetcher:async()=>new Response('<title>Title</title><article><p>本文 <a href="/source">出典</a></p><img src="https://evil.example/a"></article>',{headers:{'content-type':'text/html'}})});assert.equal(calls,1);assert.equal(result.title,'Title');assert.ok(result.markdown.includes('https://article.example/source'));assert.equal(result.sourceUrl,'https://article.example/a');assert.ok(result.convertedAt);});
test('unconnected conversion does not make any external request',async()=>{let called=false;await assert.rejects(convertUrl('https://article.example/a',{}, {fetcher:async()=>{called=true;return html();}}));assert.equal(called,false);});

test('excessively deep external HTML is rejected without recursive stack overflow',()=>{assert.throws(()=>sanitizeConversionInput('<div>'.repeat(250)+'text'+'</div>'.repeat(250),'https://article.example/a'),error=>error.status===422);});
