import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
mkdirSync('.sites-runtime',{recursive:true});
await build({entryPoints:['src/worker.mjs'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/worker-test.mjs',jsx:'automatic'});
const {createWorker}=await import('../.sites-runtime/worker-test.mjs');
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync('migrations/0001_articles.sql','utf8'));function prepare(sql,args=[]){return {bind(...a){return prepare(sql,a)},async all(){return {success:true,results:db.prepare(sql).all(...args)}},async first(){return db.prepare(sql).get(...args)||null},async run(){db.prepare(sql).run(...args);return {success:true}}};}return {prepare};}
const origin='https://reader.example';
const owner=request=>Promise.resolve(request.headers.get('x-synthetic-owner')==='yes'?{ok:true,status:200}:{ok:false,status:401});
const worker=createWorker({verifyOwner:owner,convert:async()=>({markdown:'# Converted fixture',sourceUrl:'https://article.example/',title:'Converted'})});
const data={id:'c276dbe0-bdb7-47e0-8e6c-adfa3f8a7d8d',title:'Fixture',sourceUrl:'https://example.com/a',markdown:'# Fixture\n\n<script>evil()</script>\n\n![tracking](https://evil.example/x)',published:false,rightsConfirmed:true};
const request=(path,method='GET',body,authorized=false,extra={})=>new Request(origin+path,{method,headers:{...(authorized?{'x-synthetic-owner':'yes'}:{}),...(body?{'content-type':'application/json',origin}:{}),...extra},body:body?JSON.stringify(body):undefined});
test('server rejects anonymous and unsigned owner claims on protected routes',async()=>{const env={DB:database()};for(const path of ['/admin','/api/articles','/api/convert'])assert.equal((await worker.fetch(request(path),env)).status,401);assert.equal((await worker.fetch(request('/api/articles','POST',data,false,{'oai-authenticated-user-email':'owner@example.com'}),env)).status,401);assert.equal((await worker.fetch(request('/admin','GET',undefined,true),env)).status,200);});
test('draft/public/export/unpublish state with durable SQLite and inert output',async()=>{const env={DB:database()};assert.equal((await worker.fetch(request('/api/articles','POST',data,true),env)).status,200);assert.equal((await worker.fetch(request('/p/'+data.id),env)).status,404);assert.equal((await worker.fetch(request('/export/'+data.id+'?format=md'),env)).status,404);assert.equal((await worker.fetch(request('/api/articles','POST',{...data,published:true},true),env)).status,200);const page=await worker.fetch(request('/p/'+data.id),env);assert.equal(page.status,200);const text=await page.text();assert.ok(!/<script|<img|<iframe|<form/.test(text));assert.ok(text.includes('&lt;script&gt;'));assert.ok(text.includes(data.sourceUrl));assert.equal(await (await worker.fetch(request('/export/'+data.id+'?format=md'),env)).text(),data.markdown);assert.equal((await worker.fetch(request('/api/articles','POST',data,true),env)).status,200);assert.equal((await worker.fetch(request('/p/'+data.id),env)).status,404);});
test('same-Origin JSON mutations, permission denial, safe conversion and no public writes',async()=>{const env={DB:database()};assert.equal((await worker.fetch(request('/api/articles','POST',data,true,{origin:'https://evil.example'}),env)).status,403);assert.equal((await worker.fetch(request('/api/articles','POST',{...data,published:true,rightsConfirmed:false},true),env)).status,400);assert.equal((await worker.fetch(request('/api/convert','POST',{url:'https://article.example/'},true),env)).status,200);assert.equal((await worker.fetch(request('/p/sample-safe-reading','POST',{},true),env)).status,405);assert.equal((await worker.fetch(request('/'),env)).status,200);});
